### ISSUE TITLE
Add fish shell

### ISSUE THREAD

**Issue by ALEX5402** [junegunn/fzf-git.sh#42] opened 2024-04-29 06:33 UTC
Please make a fish shell version of this config

**Comment by junegunn** [comment] 2024-04-29 07:36
Duplicate of #22

**Closed by junegunn** 2024-04-29 07:36 UTC

**Comment by ALEX5402** [comment] 2024-04-29 07:39
> Duplicate of #22

and what about nu shell ?

**Comment by junegunn** [comment] 2024-04-29 07:40
I don't even know what that is.
